name: Playground

on:
  pull_request:
    branches:
    - main
  workflow_dispatch:
    inputs:
      pr:
        description: Pull request
        type: number
        required: true

jobs:
  log:
    name: Logging
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Log Hello World
      uses: ./.github/actions/log

    - name: Get affected projects from PR files
      id: get_affected
      run: |
        affected=$(gh pr view "$PR_NUMBER" --json files --jq '[.files[].path | split("/") | .[1] | select(. != null)] | unique | join(" ")')
        echo "$affected"
        echo "affected=$affected" >> "$GITHUB_OUTPUT"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR_NUMBER: ${{ github.event.pull_request.number || github.event.inputs.pr }}

    - name: Get defined projects from angular.json
      id: get_defined
      run: |
        defined=$(jq -r '.projects | to_entries | map(select(.value.architect.test != null)) | map(.key) | join(" ")' angular.json)
        echo "$defined"
        echo "defined=$defined" >> "$GITHUB_OUTPUT"

    - name: Filter testable projects
      id: filter_testable
      run: |
        echo "$AFFECTED"
        echo "$DEFINED"
        testable=""
        for project in "$AFFECTED"; do
          echo "$project"
          if echo "$DEFINED" | grep -qx "$project"; then
            testable="$testable $project"
          fi
        done
        echo "$testable"
        testable=$(echo "$testable" | xargs) # Trim whitespace
        echo "$testable"
        echo "testable=$testable" >> "$GITHUB_OUTPUT"
      env:
        AFFECTED: ${{ steps.get_affected.outputs.affected }}
        DEFINED: ${{ steps.get_defined.outputs.defined }}
    
    - name: Run tests for each testable project
      if: steps.filter_testable.outputs.testable != ''
      run: |
        fail=0
        for project in "$TESTABLE"; do
          echo "🧪 Running tests for $project"
        done
        exit $fail
      env:
        TESTABLE: ${{ steps.filter_testable.outputs.testable }}
