name: Playground

on:
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  log:
    name: Logging
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Log pull request changed files through GitHub CLI
      env:
        GH_TOKEN: ${{ github.token }}
      run: gh pr view --json files
