name: Playground

on:
  pull_request:
    branches:
    - main
  workflow_dispatch:

env:
  PR_NUMBER: ${{ github.event.number }}

jobs:
  log:
    name: Logging
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Log all pull request
      run: gh pr list
    - name: Log all changed files
      run: h pr view $PR_NUMBER --json files --jq '[.files[].path]'
    - name: Log all second segments
      run: gh pr view $PR_NUMBER --json files --jq '[.files[].path | split("/") | .[1]] | unique'
