name: Playground

on:
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  log:
    name: Logging
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Log all pull request
      run: gh pr list
    - name: Log pull request changed files
      run: gh pr view --json files
