name: Playground

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

  workflow_dispatch:
    inputs:
      pr:
        description: Pull request number
        type: number
        required: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup browser
      uses: ./.github/actions/setup-browser

    - name: Get testable projects
      id: testable
      uses: ./.github/actions/get-affected
      with:
        architect: test
        pr: $PR_number
      env:
        PR_NUMBER: ${{ github.event.pull_request.number || github.event.inputs.pr }}

    - name: Run tests for each testable project
      if: steps.testable.outputs.affected != ''
      run: |
        fail=0
        for project in $TESTABLE; do
          echo "🧪 Running tests for $project"
        done
        exit $fail
      env:
        TESTABLE: ${{ steps.testable.outputs.affected }}
